apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 588515432336.dkr.ecr.us-east-1.amazonaws.com/order
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: FLASK_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: python-ms-configmap
                  key: host
            - name: FLASK_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: python-ms-configmap
                  key: port
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
