apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: XXX.dkr.ecr.us-east-1.amazonaws.com/profile
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: FLASK_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: python-ms-configmap
                  key: host
            - name: FLASK_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: python-ms-configmap
                  key: port
            - name: DDB_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: python-ms-configmap
                  key: ddb_table
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
