AWSTemplateFormatVersion: '2010-09-09'
Description: >

  This Cloudformation Template deploys the Redis Cluster (Amazon ElastiCache).

  Disclaimer: Not for production use. Demo and testing purposes only.

  Author: Bastian Klein <basklein@amazon.com>, Modified by Zach Gardner <gardz@amazon.com>

Parameters:
  VPC:
    Description: Reference for the VPC in which to deploy Amazon ElastiCache
    Type: String
  RedisInstanceType:
    Description: Instance type for Amazon ElastiCache (Redis)
    Type: String
    AllowedValues:
      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium
  PrivateDBSubnets:
    Description: Comma separated list of the private database subnets
    Type: CommaDelimitedList
  ElasticacheSecurityGroup:
    Description: Security Group used for the ElastiCache instances
    Type: String
Resources:
  CacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: CacheSubnetGroup
      SubnetIds: !Ref PrivateDBSubnets
  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: CacheSubnetGroup
      SubnetIds: !Ref PrivateDBSubnets
  ElastiCacheRedisCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    DependsOn: ElastiCacheSubnetGroup
    Properties:
      AutoMinorVersionUpgrade: true
      CacheParameterGroupName: "default.redis6.x.cluster.on"
      CacheNodeType: cache.t3.micro
      CacheSubnetGroupName:  !Ref ElastiCacheSubnetGroup
      Engine: redis
      EngineVersion: "6.x"
      NumNodeGroups: 3
      Port: 6379
      ReplicasPerNodeGroup: 1
      ReplicationGroupDescription: ElastiCache Microservices Demo
      SecurityGroupIds:
        - !Ref ElasticacheSecurityGroup
Outputs:
  DBAddress:
    Description: Database Address
    Value: !GetAtt  ElastiCacheRedisCluster.ConfigurationEndPoint.Address
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", DBAddress ] ]
  DBPort:
    Description: Database Port
    Value: "6379"
  ElasticacheRedis:
    Description: Redis Cluster
    Value: !Ref ElastiCacheRedisCluster
  CacheSubnetGroup:
    Description: Redis Subnet Group
    Value: !Ref CacheSubnetGroup