apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard
  labels:
    app: leaderboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      containers:
        - name: leaderboard
          image: 588515432336.dkr.ecr.us-east-1.amazonaws.com/leaderboard
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: FLASK_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: python-ms-configmap
                  key: host
            - name: FLASK_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: python-ms-configmap
                  key: port
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
